name: klarete
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  colorful_safe_area: ^0.3.0
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.6.0
  http: ^0.13.4



dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Jost
      fonts:
        - asset: lib/fonts/Jost-VariableFont_wght.ttf
        - asset: lib/fonts/Jost-Italic-VariableFont_wght.ttf

  assets:
    - assets/

  uses-material-design: true
